Feature/user
codestates-seb/seb41_main_012 pull request #59
Opened 2023-01-22 05:13 UTC by dlawnsdh

## What is this PR?(작업 내용) :mag:
- Webflux를 사용하여 리액티브하게 구성
- OAuth2를 사용한 소셜 로그인
- 로그인 성공 시 JWT 발급
- 유저 관련 기능 작성
  - 마이페이지 조회 
  - ID값으로 해당 유저 조회 기능
  - 닉네임 검색 
  - 회원 정보 수정 
- 팔로우 관련 기능 작성
  - 팔로우 등록 
  - 팔로우 취소
  - 팔로잉 목록 조회
  - 팔로워 목롣 조회

## review point :memo:
- 팔로우 테이블을 회원ID 값에서 회원 이메일로 변경 
  - 토큰 검증시 이메일을 사용하기 때문에 ID값으로 팔로우 테이블을 만들면 유저 이메일로 한번 더 유저를 조회하여 ID값을 가 
    져와야 하므로 불필요한 조회 과정이 추가됨 
- 'MemberCustomRepository'에 대한 리팩토링이 필요해 보임

## Background(문제 배경) 🖼️ 
- JPA는 시큐리티 필터 체인을 구성할 때 HttpSecurity를 사용하여 구현하는데 이때 oauth2Login이라는 메소드에 체이닝으로 userInfoEndpoint라는 함수가 있어서 OAuth2UserService를 구현한 후 넣어주면 됐었는데 webflux에서는 ServerHttpSecurity 를 사용합니다. HttpSecurity와 ServerHttpSecurity 는 구조가 좀 달라서 ReactiveOAuth2UserService의 반환 값을 어떻게 가져와야 하나 고민이 많이 되었는데 디버깅을 해보니 빈으로 등록되어 핸들러에서 authentication 객체로 가져올 수 있었습니다 

## important(같이 논의할 내용) ❓ 
- MemberCustomRepository의 findWithFollow 메서드의 효율성 논의 필요

2023-01-22 09:45 UTC, hie6953 commented on server/matp/src/main/java/com/matp/auth/config/SecurityConfig.java
> +     * 매 요텅마다 검증하기위해 addfilterAt에서 HTTP_BASIC에 걸어둠
토크, 요텅 오타 수정 부탁드립니다

2023-01-22 12:41 UTC, hie6953 requested changes
고생하셨습니다!
저도 팔로잉에 이메일 사용한것과 비슷한 문제를 겪고 있어서 어떻게 해야할지 같이 고민해보자고 써뒀었는데, 이메일로 통일해서 전부 처리할지 인증정보에 id값을 넘길지 얘기하면 좋을 것 같습니다
findWithFollow 메서드 MemberResponse.from안에 멤버를 만들고 다시 매핑하는 게 비효율적인 것 같긴 하네요

2023-01-22 12:41 UTC, hie6953 commented on server/matp/src/main/java/com/matp/follow/controller/FollowController.java
> +    private String extractEmail(ServerHttpRequest request) {
@AuthenticationPrincipal를 사용해서 유저정보 가져오는건 안되나요?
JwtAuthenticationFIlter.java에서 검증에 성공하면 아래 작성하신 코드처럼 저장을 합니다
```
return chain.filter(exchange).contextWrite(ReactiveSecurityContextHolder.withAuthentication(authentication));
```
ContextHolder에 Authentication 객체를 저장하면 @AuthenticationPrincipal으로 토큰 안에 넘긴 정보를 가져올 수 있는 것으로 알고 있습니다
레퍼런스
https://velog.io/@jyleedev/AuthenticationPrincipal-%EB%A1%9C%EA%B7%B8%EC%9D%B8-%EC%A0%95%EB%B3%B4-%EB%B0%9B%EC%95%84%EC%98%A4%EA%B8%B0

2023-01-22 12:57 UTC, hie6953 commented on server/matp/src/main/java/com/matp/follow/controller/FollowController.java
> +    private String extractEmail(ServerHttpRequest request) {
webflux에서는 이런식으로 하는 것 같습니다
https://godekdls.github.io/Spring%20Security/oauth2webflux/

2023-01-23 02:25 UTC, dlawnsdh commented on server/matp/src/main/java/com/matp/auth/config/SecurityConfig.java
> +     * 매 요텅마다 검증하기위해 addfilterAt에서 HTTP_BASIC에 걸어둠
cors 작성할 때 수정해서 다시 올리겠습니다

2023-01-23 02:50 UTC, dlawnsdh commented on server/matp/src/main/java/com/matp/follow/controller/FollowController.java
> +    private String extractEmail(ServerHttpRequest request) {
저는 토큰 사용해서 이메일 가져올 때 검증 과정이 한번 더 있기도 하고 토큰 인증 방식이라 일부러 저렇게 했었는데
고민을 더 해봐야 할 것 같습니다

2023-01-23 06:48 UTC, ke2007 reviewed
👍

2023-01-23 06:48 UTC, ke2007 approved these changes

2023-01-24 04:43 UTC, hie6953 approved these changes

2023-01-24 05:49 UTC, woodyplt approved these changes
webflux가 익숙하지 않을텐데 개발하느라 고생하셨습니다👍👍👍

2023-01-24 05:49 UTC, woodyplt commented on server/matp/src/main/java/com/matp/auth/config/SecurityConfig.java
> +                /*.exceptionHandling(exceptionHandlingSpec -> exceptionHandlingSpec
사용되지 않는 코드는 제거되는게 좋을 것 같습니다.
어떤 이유에서 남겨둬야 한다면 코멘트를 추가하는 것이 추후 파악에 용이할 것 같다는 생각이 듭니다😀

2023-01-24 05:49 UTC, woodyplt commented on server/matp/src/main/java/com/matp/auth/dto/GoogleOAuth2Response.java
> +public record GoogleOAuth2Response(
map 연산을 객체로 위임하고 principal을 생성하는 것은 좋은 것 같습니다👍
다만, 지금처럼 단순 매핑 역할만 한다면 매번 객체를 생성하는 것이 아닌 유틸(static)로도 충분하지 않을까 생각이 듭니다.

```java
PrincipalMapper.somting()
PrincipalConverter.somthing()
```

2023-01-24 05:49 UTC, woodyplt commented on server/matp/src/main/java/com/matp/auth/dto/KakaoOAuth2Response.java
> +            public static Profile from(Map<String, Object> attributes) {
Profile의 팩토리 생성자 메서드를 별도로 만든 이유가 있을까요??
KakaoAccount의 필수값이라면 KakaoAccount의 팩토리 생성자 메서드로 충분하지 않을까 생각이 듭니다.

2023-01-24 05:49 UTC, woodyplt commented on server/matp/src/main/java/com/matp/auth/handler/OAuthSuccessHandler.java
> +        log.info("accessToken: {}", accessToken);
로그 메시지를 보아 디버깅 용도로 보이는데요. 적절한 level로 설정해두면 좋을 것 같습니다!

2023-01-24 05:49 UTC, woodyplt commented on server/matp/src/main/java/com/matp/auth/handler/OAuthSuccessHandler.java
> +public class OAuthSuccessHandler implements ServerAuthenticationSuccessHandler {
OauthSuccessHandler는 로그인 생성시 매번 생성되는 구조로 보이는데요. 이유가 있을까요?
작성된 코드로 보아 싱글톤으로 사용될 수 있을 것 같아서 질문드립니다!

2023-01-24 05:49 UTC, woodyplt commented on server/matp/src/main/java/com/matp/follow/entity/Follow.java
> +    @Setter private String followerEmail;
해당 필드는 다른 테이블과 릴레이션(외래키)을 가지는게 맞을까요?
일반적으로 외래키는 대상 테이블의 기본키와 릴레이션를 가지긴 합니다..

JWT 생성시 payload로 기본키(id)를 넣어준다면 불필요한 과정이 해결되지 않을까요??🙋

2023-01-24 13:54 UTC, merged